### ISSUE TITLE
Interactive Plot

### ISSUE THREAD

**Issue by Dmacracy** [Dmacracy/st159_Lab7#7]
- [x] Make a projectile notebook
- [x] Make `plot_projectile_motion` an interactive function using the interact decorator.

**Comment by Dmacracy** [comment]
I'm starting to work on this.

**Comment by Dmacracy** [comment]
Oh I realized this needs to be an .ipynb first. So now I need to create a notebook first.

**Comment by ruijis** [comment]
how to add participants?

**Comment by ruijis** [comment]
I can unassign myself

**Comment by Dmacracy** [comment]
Notebook created still have to make interactive. 

As a collaborator, I can even edit Daniel'ss comment. (From Ricky)

**Comment by Dmacracy** [comment]
All done!

**Comment by Dmacracy** [comment]
[`projectiles.py`](https://github.com/Dmacracy/st159_Lab7/blob/main/src/projectiles.py)
